global:
  scrape_interval: 5s  # Częstotliwość pobierania metryk

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # cAdvisor zbiera metryki kontenerów
